name: koemoe
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - brotli-python=1.0.9
  - ca-certificates=2024.3.11
  - certifi=2024.6.2
  - charset-normalizer=2.0.4
  - cpuonly=2.0
  - filelock=3.13.1
  - freetype=2.12.1
  - gmpy2=2.1.2
  - idna=3.7
  - jinja2=3.1.4
  - jpeg=9e
  - lcms2=2.12
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.4
  - libjpeg-turbo=2.0.0
  - libpng=1.6.39
  - libtiff=4.5.1
  - libuv=1.44.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpir=3.0.0
  - mpmath=1.3.0
  - networkx=3.1
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openjpeg=2.4.0
  - openssl=3.0.14
  - pillow=10.3.0
  - pip=24.0
  - pysocks=1.7.1
  - python=3.8.19
  - pytorch=2.3.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - requests=2.32.2
  - setuptools=69.5.1
  - six=1.16.0
  - sqlite=3.45.3
  - sympy=1.12
  - torchaudio=2.3.1
  - torchvision=0.18.1
  - typing_extensions=4.11.0
  - urllib3=2.2.2
  - vc=14.2
  - vs2015_runtime=14.29.30133
  - wheel=0.43.0
  - win_inet_pton=1.1.0
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - ansicon==1.89.0
      - blessed==1.20.0
      - cffi==1.16.0
      - click==8.1.7
      - colorama==0.4.6
      - contourpy==1.1.1
      - cycler==0.12.1
      - decorator==5.1.1
      - enlighten==1.12.4
      - fastai==2.7.15
      - fastcore==1.5.48
      - fonttools==4.53.1
      - fsspec==2024.6.1
      - importlib-metadata==8.0.0
      - importlib-resources==6.4.0
      - intel-openmp==2021.4.0
      - jinxed==1.2.1
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - librosa==0.10.2.post1
      - llvmlite==0.41.1
      - markdown-it-py==3.0.0
      - matplotlib==3.7.5
      - mdurl==0.1.2
      - mkl==2021.4.0
      - msgpack==1.0.8
      - numba==0.58.1
      - packaging==24.1
      - pandas==2.0.3
      - platformdirs==4.2.2
      - pooch==1.8.2
      - prefixed==0.7.1
      - pycparser==2.22
      - pygments==2.18.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - python-ffmpeg==2.0.12
      - pytz==2024.1
      - rich==13.7.1
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - smart-open==7.0.4
      - soxr==0.3.7
      - tbb==2021.13.0
      - threadpoolctl==3.5.0
      - tqdm==4.66.4
      - tzdata==2024.1
      - wcwidth==0.2.13
      - wrapt==1.16.0
      - zipp==3.19.2
      - "git+https://github.com/jboy/ffprobe3-python3.git@1aa2baa4a9197b5180b3a95836b6667f491fcbe0"
